name: HACS

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "integration"
